# SPDX-License-Identifier: Apache-2.0

pekko {
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  loglevel = "DEBUG"
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
  actor.provider = cluster
}

pekko.management {
  cluster.bootstrap {
    contact-point-discovery {
      discovery-method = kubernetes-api
      required-contact-point-nr = ${REQUIRED_CONTACT_POINT_NR}
    }
  }
}

pekko.rollingupdate.kubernetes {
  # for documentation purposes, 3 is the default anyway
  pod-deletion-cost.annotated-pods-nr = 3
}
