name: Headers

on:
  pull_request:

permissions: {}

jobs:
  check-headers:
    name: Check headers
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Coursier cache
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1

      - name: Check headers
        run: sbt +headerCheckAll
