name: Integration test for Kubernetes DNS

on:
  pull_request:
  push:
    branches:
      - main
      - release-*
    tags-ignore: [ v.* ]
  schedule:
    - cron: '0 2 * * *'  # every day 2am

jobs:
  integration-test:
    name: Integration Tests for Kubernetes DNS
    runs-on: ubuntu-22.04
    if: github.repository == 'apache/pekko-management'
    strategy:
      fail-fast: false    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Install sbt
        uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1.1.19

      - name: Cache Coursier cache
        uses: coursier/cache-action@e47d7d35a0d3a2c7f649ca5c63dfc2bbfaa002e7 # v8.0.1

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@e5e04bedd6f05f888ec4af65a0fa716430b21fec # v2.16.0
        with:
          minikube version: 'v1.36.0'
          kubernetes version: 'v1.29.15'
          driver: docker
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=ingress'

      - name: Run Integration Tests
        run: |-
          ./integration-test/kubernetes-dns/test.sh

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
