name: Integration test for Kubernetes API with Maven

on:
  pull_request:
  push:
    branches:
      - main
      - release-*
    tags-ignore: [ v.* ]
    # Different from its siblings, we don't configure this workflow to run as a cron job.

jobs:
  integration-test:
    name: Integration Tests for Kubernetes API with Maven
    runs-on: ubuntu-20.04
    if: github.repository == 'apache/pekko-management'
    strategy:
      fail-fast: false    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.11.0
        with:
          minikube version: 'v1.27.1' # based on k8s v1.25.2
          kubernetes version: 'v1.25.2'
          driver: docker
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=ingress'

      - name: Start docker
        run: |-
          ./integration-test/kubernetes-api-java/test.sh

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
