name: Publish 1.0 docs

on:
  workflow_dispatch:

jobs:
  publish-docs:
    name: Publish 1.0 documentation to nightlies.apache.org
    runs-on: ubuntu-latest
    if: github.repository == 'apache/pekko-management'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: 1.0.x

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 8

      - name: Install sbt
        uses: sbt/setup-sbt@26ab4b0fa1c47fa62fc1f6e51823a658fb6c760c # v1.1.7          

      - name: Cache Coursier cache
        uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # v6.4.7

      - name: Build Documentation
        run: |-
          sbt "set ThisBuild / version := \"1.0.0\"; docs/paradox; unidoc"
        env:
          JAVA_OPTS: "-verbose:gc -Xmx4g"

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-management/1.0.0/
          mkdir -p target/nightly-docs/docs/pekko-management/1.0/
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-management/1.0.0/docs
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-management/1.0/docs
          rm -r docs/target/paradox/site/main/
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-management/1.0.0/api
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-management/1.0/api
          rm -r target/scala-2.13/unidoc

      - name: Upload 1.0.x nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-management/1.0.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

      - name: Upload 1.0 nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-management/1.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}          
