on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Launch Scala Steward
    if: github.repository == 'apache/pekko-management'
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@026472ebc0e1f80577b240b249e3dc1494e7041b # v2.86.0
        env:
          JAVA_OPTS: "-Xms1G -Xmx1G -Xss2M -XX:ReservedCodeCacheSize=128m"
        with:
          github-app-id: ${{ secrets.SCALA_STEWARD_APP_ID }}
          github-app-installation-id: ${{ secrets.SCALA_STEWARD_INSTALLATION_ID }}
          github-app-key: ${{ secrets.SCALA_STEWARD_PRIVATE_KEY }}
          github-app-auth-only: true
